spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/sb_security_jwt__test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: imhope
    password: 0987
